### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by giuseppecartella** [DiGyt/cateyes#8]
Hi,
When installing the package through the provided command I get the following error:

`error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [77 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-310
      creating build\lib.win-amd64-cpython-310\nslr
      copying nslr\slow_nslr.py -> build\lib.win-amd64-cpython-310\nslr
      copying nslr\__init__.py -> build\lib.win-amd64-cpython-310\nslr
      running build_ext
      building 'nslr.cppnslr' extension
      Traceback (most recent call last):
        File "C:\Users\Cartella Giuseppe\AppData\Local\Temp\pip-install-gc8d8rvr\nslr_bae510abf886422c9ae5dea41dd1069a\setup.py", line 125, in build_extensions  
          return self._do_build_extensions()
        File "C:\Users\Cartella Giuseppe\AppData\Local\Temp\pip-install-gc8d8rvr\nslr_bae510abf886422c9ae5dea41dd1069a\setup.py", line 121, in _do_build_extensions
          build_ext.build_extensions(self)
        File "C:\Users\Cartella Giuseppe\anaconda3\envs\my_new_env\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 467, in build_extensions  
          self._build_extensions_serial()
        File "C:\Users\Cartella Giuseppe\anaconda3\envs\my_new_env\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 493, in _build_extensions_serial
          self.build_extension(ext)
        File "C:\Users\Cartella Giuseppe\anaconda3\envs\my_new_env\lib\site-packages\setuptools\command\build_ext.py", line 246, in build_extension
          _build_ext.build_extension(self, ext)
        File "C:\Users\Cartella Giuseppe\anaconda3\envs\my_new_env\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 548, in build_extension   
          objects = self.compiler.compile(
        File "C:\Users\Cartella Giuseppe\anaconda3\envs\my_new_env\lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 343, in compile
          self.initialize()
        File "C:\Users\Cartella Giuseppe\anaconda3\envs\my_new_env\lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 253, in initialize
          vc_env = _get_vc_env(plat_spec)
        File "C:\Users\Cartella Giuseppe\anaconda3\envs\my_new_env\lib\site-packages\setuptools\msvc.py", line 214, in msvc14_get_vc_env
          return _msvc14_get_vc_env(plat_spec)
        File "C:\Users\Cartella Giuseppe\anaconda3\envs\my_new_env\lib\site-packages\setuptools\msvc.py", line 168, in _msvc14_get_vc_env
          raise distutils.errors.DistutilsPlatformError(
      distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
     
      During handling of the above exception, another exception occurred:
     
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Cartella Giuseppe\AppData\Local\Temp\pip-install-gc8d8rvr\nslr_bae510abf886422c9ae5dea41dd1069a\setup.py", line 171, in <module>
          try_setup(True)
        File "C:\Users\Cartella Giuseppe\AppData\Local\Temp\pip-install-gc8d8rvr\nslr_bae510abf886422c9ae5dea41dd1069a\setup.py", line 169, in try_setup
          setup(**params)
        File "C:\Users\Cartella Giuseppe\anaconda3\envs\my_new_env\lib\site-packages\setuptools\__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\Cartella Giuseppe\anaconda3\envs\my_new_env\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
        File "C:\Users\Cartella Giuseppe\anaconda3\envs\my_new_env\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\Cartella Giuseppe\anaconda3\envs\my_new_env\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\Cartella Giuseppe\anaconda3\envs\my_new_env\lib\site-packages\setuptools\dist.py", line 1234, in run_command
          super().run_command(command)
        File "C:\Users\Cartella Giuseppe\anaconda3\envs\my_new_env\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\Cartella Giuseppe\anaconda3\envs\my_new_env\lib\site-packages\wheel\bdist_wheel.py", line 325, in run
          self.run_command("build")
        File "C:\Users\Cartella Giuseppe\anaconda3\envs\my_new_env\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\Cartella Giuseppe\anaconda3\envs\my_new_env\lib\site-packages\setuptools\dist.py", line 1234, in run_command
          super().run_command(command)
        File "C:\Users\Cartella Giuseppe\anaconda3\envs\my_new_env\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\Cartella Giuseppe\anaconda3\envs\my_new_env\lib\site-packages\setuptools\_distutils\command\build.py", line 131, in run
          self.run_command(cmd_name)
        File "C:\Users\Cartella Giuseppe\anaconda3\envs\my_new_env\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\Cartella Giuseppe\anaconda3\envs\my_new_env\lib\site-packages\setuptools\dist.py", line 1234, in run_command
          super().run_command(command)
        File "C:\Users\Cartella Giuseppe\anaconda3\envs\my_new_env\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\Cartella Giuseppe\anaconda3\envs\my_new_env\lib\site-packages\setuptools\command\build_ext.py", line 84, in run
          _build_ext.run(self)
        File "C:\Users\Cartella Giuseppe\anaconda3\envs\my_new_env\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 345, in run
          self.build_extensions()
        File "C:\Users\Cartella Giuseppe\AppData\Local\Temp\pip-install-gc8d8rvr\nslr_bae510abf886422c9ae5dea41dd1069a\setup.py", line 127, in build_extensions  
          raise BuildFailed()
      __main__.BuildFailed
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for nslr
ERROR: Could not build wheels for nslr, which is required to install pyproject.toml-based projects`

Any hints on how to solve?
Thank you in advance

**Comment by DiGyt** [comment]
Hey there :)

With the provided command, do You mean:
`pip install git+https://github.com/DiGyt/cateyes.git`?

If yes, this looks like an issue which occurs specifically in your environment. Are You using this on Windows and potentially with MS Visual Studio? Judging from the output, this is either an issue with the setuptools library, or MS Visual Studio, but unfortunately this does not look like something over which we have the power to fix :/

Here is a stackoverflow entry for similar errors produced during installation of other Python libraries:

https://stackoverflow.com/questions/64261546/how-to-solve-error-microsoft-visual-c-14-0-or-greater-is-required-when-inst

Maybe this would help with finding a solution?

Feel free to ask back if You feel like it's an issue that we can fix within this toolbox, but also feel free to let us know and close the issue if you made it work :)

**Comment by giuseppecartella** [comment]
It is a Windows-related problem. I did not investigate the reasons but running on a Linux environment doesn't raise any issue!
Thank you for your support!
Giuseppe
